src/Entity/File.php
<?php

namespace App\Entity;

use App\Repository\FileRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FileRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class File
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $size;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Folder::class, inversedBy="files")
     */
    private $subFolder;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $brochureFilename;

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $dateTimeNow = new DateTime('now');

        $this->setUpdatedAt($dateTimeNow);

        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt($dateTimeNow);
        }
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getSubFolder(): ?Folder
    {
        return $this->subFolder;
    }

    public function setSubFolder(?Folder $subFolder): self
    {
        $this->subFolder = $subFolder;

        return $this;
    }

    public function getBrochureFilename(): ?string
    {
        return $this->brochureFilename;
    }

    public function setBrochureFilename(string $brochureFilename): self
    {
        $this->brochureFilename = $brochureFilename;

        return $this;
    }

}

src/Form/FileType.php
<?php

namespace App\Form;

use App\Entity\File;
use App\Entity\Folder;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType as TypeFileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File as FileConstaint;

class FileType extends AbstractType
{
    
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom : <span class="text-danger">*</span>',
                'label_html' => true
            ])
            ->add('brochure', TypeFileType::class, [
                'label' => 'Fichier(s) : <span class="text-danger">*</span>',
                'label_html' => true,
                'mapped' => false,
            ])
            ->add('subFolder', EntityType::class, [
                'class' => Folder::class,
                'placeholder' => 'Aucun dossier',
                'required' => false,
                'label' => 'Dans le dossier :'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => File::class,
        ]);
    }
}

src/Controller/FileController.php
<?php

namespace App\Controller;

use App\Entity\File;
use App\Entity\Folder;
use App\Form\FileType;
use App\Form\FolderType;
use App\Repository\FileRepository;
use App\Repository\FolderRepository;
use App\Service\UploadManager;
use Doctrine\ORM\QueryBuilder;
use Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter;
use Omines\DataTablesBundle\Column\TextColumn;
use Omines\DataTablesBundle\DataTableFactory;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/')]
class FileController extends AbstractController
{
    private $file;

    #[Route('/', name: 'default', methods: ['GET', 'POST'])]
    public function index(): Response
    {
        return $this->redirectToRoute('folder_index');
    }

    #[Route('/{id}', name: 'file_show', methods: ['GET', 'POST'], requirements: ['id' => '\d+'])]
    public function show(File $file): Response
    {
        return $this->render('file/show.html.twig', [
            'file' => $file
        ]);
    }


    #[Route('/new', name: 'file_new', methods: ['POST'])]
    public function new(Request $request, UploadManager $uploadManager): Response
    {
        $file = new File();
        $form = $this->createForm(FileType::class, $file);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $brochureFile = $form->get('brochure')->getData();
            if ($brochureFile) {
                [$brochureFileName, $size, $type] = $uploadManager->upload($brochureFile);
                $file->setBrochureFilename($brochureFileName);
                $file->setSize($size);
                $file->setType($type);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($file);
            $entityManager->flush();

            $this->addFlash('success', 'Folder added successfully !');
            return $this->redirectToRoute('default');
        }

        $this->addFlash('error', 'Une erreur est survenue !');
        return $this->redirectToRoute('default');
    }

    #[Route('/{id}/edit', name: 'file_edit', methods: ['GET','POST'])]
    public function edit(Request $request, File $file): Response
    {
        $form = $this->createForm(FileType::class, $file);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('file_show', [
                'id' => $file->getId()
            ]);
        }

        return $this->renderForm('file/edit.html.twig', [
            'file' => $file,
            'fileForm' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'file_delete', methods: ['POST'])]
    public function delete(Request $request, File $file, UploadManager $uploadManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$file->getId(), $request->request->get('_token'))) {
            $uploadManager->delete($file->getBrochureFilename());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($file);
            $entityManager->flush();
        }

        return $this->redirectToRoute('default');
    }
}

templates/file/_delete_form.html.twig
<form method="post" action="{{ path('file_delete', {'id': file.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ file.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/file/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/file/_update.html.twig
{{ form_start(fileForm) }}
    {{ form_widget(fileForm) }}
    <button class="btn btn-success">{{ button_label|default('Ajouter') }}</button>
{{ form_end(fileForm) }}

templates/file/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Edit File</h1>
    {{ include('file/_update.html.twig', {'button_label': 'Update'}) }}

    <div class="row">
        <div class="col-md-6">
                <a href="{{ path('file_show', {id: file.id}) }}" class="btn btn-primary">Retour</a>
        </div>
        <div class="col-md-6">
            {{ include('file/_delete_form.html.twig') }}
        </div>
    </div>

{% endblock %}

templates/file/show.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    <a href="{{ path('files_index', {'id': customer_id}) }}" class="btn btn-primary">Retour</a>
{% endblock %}
{% block body %}
    <table class="table">
        <tbody>
            <tr>
                <th># :</th>
                <td>{{ file.id }}</td>
            </tr>
            <tr>
                <th>Aperçu :</th>
                <td>
                    {% if 'video' in file.type %}
                        <video controls>
                            <source type="{{file.type}}" src="/uploads/{{file.brochureFilename}}"></source>
                        </video>
                    {% endif %}
                    <embed src="/uploads/{{file.brochureFilename}}" width="200px">
                </td>
            </tr>
            <tr>
                <th>Nom du fichier :</th>
                <td>{{ file.brochureFilename }}</td>
            </tr>
            <tr>
                <th>Nom du dossier :</th>
                <td>{{ file.subFolder.name ?? 'Pas de dossier' }}</td>
            </tr>
            <tr>
                <th>Créer le :</th>
                <td>{{ file.createdAt ? file.createdAt|date('d-m-Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Modifier le :</th>
                <td>{{ file.updatedAt ? file.updatedAt|date('d-m-Y H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    
    <div class="col mt-4">
        <div class="row">
            <a href="/uploads/{{file.brochureFilename}}" class="btn btn-info">Regarder</a>
            <a href="/uploads/{{file.brochureFilename}}" class="btn btn-success" download="{{file.name}}">Télécharger</a>
            <button onclick="printJS('/uploads/{{file.brochureFilename}}', {{file.brochureFilename|split('.')|last == 'pdf' ? '' : "'image'"}})" class="btn btn-warning">Imprimer</button>
            <a href="{{ path('file_edit', {'id': file.id}) }}" class="btn btn-primary">Modifier</a>
            {{ include('file/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/print-js/1.5.0/print.min.js" integrity="sha512-lzGE9ZqdrztBEk1wtq4O60N3WbsTlIvvm6ULCxWRt+CwpRD4WUbgC5aatbtourCUC15PJpqcpZk3VLs12vpNoA==" crossorigin="anonymous"></script>
{% endblock %}